name: Test

on: [push]

jobs:
  test:
    # we run the CI on windows for 2 reasons:
    #  1. ubuntu-latest doesn't support osmconvert without installing libz.so
    #  2. our fork of pbf2json only has pre-build bindaries for windows & macos
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: ⏬ switch off autocrlf
        # see https://github.com/actions/checkout/issues/135
        run: git config --global core.autocrlf false

      - name: ⏬ Checkout code
        uses: actions/checkout@v3

      - name: 🔢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⏬ Install
        run: |
          npm install
          git reset --hard
        # ^ if the lockfile changed, remove it from the git diff

      - name: ✨ Lint
        run: |
          npm run lint

      - name: 🔣 Validate taginfo.json
        run: |
          node -e 'require("./taginfo.json")'

      - name: 🧪 Test
        run: |
          mkdir -p data
          npm run test:ci
        env:
          FORCE_COLOR: 1
          LINZ_API_KEY: ${{ secrets.LINZ_API_KEY }}

      - name: 😥 Print snapshot diff on failure
        if: failure()
        run: |
          git diff --color=always

      - name: 📈 Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
        continue-on-error: true
